name: 24x7 Pro Stream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

concurrency: 
  group: live-stream
  cancel-in-progress: true

jobs:
  stream:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install ffmpeg python3 python3-pip -y
          pip3 install gdown requests --break-system-packages

      - name: Run Auto-Streamer Script
        env:
          YOUTUBE_URL: rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: timeout 5.5h python3 stream.py || true

      - name: Auto-Restart Stream (Relay Race)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run "24x7 Pro Stream"
