name: 24x7 Pro Stream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Har 5 ghante me auto-restart

concurrency: 
  group: live-stream
  cancel-in-progress: true

jobs:
  stream:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout Repo (Get Files)
        uses: actions/checkout@v3

      - name: Install FFmpeg & Python
        run: sudo apt update && sudo apt install ffmpeg python3 -y

      - name: Run Auto-Streamer Script
        env:
          YOUTUBE_URL: rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}
        # 5.5 ghante stream chalegi, uske baad script apne aap stop hogi
        run: timeout 5.5h python3 stream.py || true

      - name: Auto-Restart Stream (Relay Race)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run "24x7 Pro Stream"
